export interface UserMock {
  [key: string]: {
    active: boolean;
    currentMatch: string;
    email: string;
    firstName: string;
    lastName: string;
    location: number;
    matchConfirmed: boolean;
    matches: { [key: string]: number };
  };
}

export const usersData = {
  '-KgOqYdDS7YnTtBqzRiY': {
    active: false,
    currentMatch: '',
    email: 'viviana.ramirez@yuxiglobal.com',
    firstName: 'Marcela',
    lastName: 'Ramirez',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOrENdp6v7JQwZSHui': 1,
      '-KgOscV90waV1yADszBC': 1,
      '-KgOv2t076F9-t5yU0bR': 1,
      '-KgOw9idQAbYbuT3k6gk': 1,
    },
  },
  '-KgOqbnhcAip7FTS4svi': {
    active: true,
    currentMatch: '-KgOsT6XWWe3psX3Kk27',
    email: 'cindy.giraldo@yuxiglobal.com',
    firstName: 'Cindy',
    lastName: 'Giraldo',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOr6FlNMaAa-FUEbXG': 1,
      '-KgOr9wtNW_Xj8jGiX5S': 1,
      '-KgOsxfP-fNbH_7iOO8-': 1,
      '-KgOuI6H-p-sRssyGKgy': 1,
      '-KgOv-CH56cFUVSH2TrK': 1,
      '-KgOvApPFJdB3FRFQF1H': 1,
      '-KgOvkvmV9ki8L2F4wn1': 1,
      '-KgOw1jekIf09IoMvPEu': 1,
      '-KrHqrY1u2GdAl8ut7WV': 1,
    },
  },
  '-KgOqj7LMMxnP21GLFi3': {
    active: true,
    currentMatch: '-KgOts51IfcFm-CG3G29',
    email: 'williams.munoz@yuxiglobal.com',
    firstName: 'Jhon',
    lastName: 'Muñoz',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOqpjLOMXrEE1d1q3C': 1,
      '-KgOrMKlm7c5jmb8kuqV': 1,
      '-KgOsxfP-fNbH_7iOO8-': 1,
      '-KgOtbhexS_IIXj6OfFA': 1,
      '-KgOuZMHj59C5xujEcfv': 1,
      '-KgOv679TGhuCce7go8K': 1,
      '-KgOvkvmV9ki8L2F4wn1': 1,
      '-KgoUaofJtY5mhveO1EH': 1,
      '-Kntmfcpd7627UdsUoUh': 1,
    },
  },
  '-KgOqpjLOMXrEE1d1q3C': {
    active: true,
    currentMatch: '-KyWpcaTm0Pw2cJCAGre',
    email: 'carlos.angulo@yuxiglobal.com',
    firstName: 'Carlos',
    lastName: 'Angulo',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOqj7LMMxnP21GLFi3': 1,
      '-KgOr_at59hfkyWhxpZa': 1,
      '-KgOtIkeqwAfKNQwzzdI': 1,
      '-KgOtwCHHUqbF53m_72g': 1,
      '-KgOu1L99pQipAt_GPh3': 1,
      '-KgOvbJnHXFFk9IBqbSb': 1,
      '-KgOvebeq2vEcRECjba9': 1,
      '-KgOwSDWw8_OxrNFbRlD': 1,
      '-KnqjtRVFva3fYeSFn5G': 1,
    },
  },
  '-KgOqtl5OarpOeSbv5L5': {
    active: false,
    currentMatch: '',
    email: 'deicy.martinez@yuxiglobal.com',
    firstName: 'Carolina',
    lastName: 'Martinez',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOrr4lyPlcujBvbqyv': 1,
      '-KgOs4yXXBiQ62hBV67x': 1,
      '-KgOuotfdOsLHVs2jffl': 1,
    },
  },
  '-KgOr6FlNMaAa-FUEbXG': {
    active: true,
    currentMatch: '-KyWpcaSt2iwMuN0EMAg',
    email: 'carlos.arbelaez@yuxiglobal.com',
    firstName: 'Carlos',
    lastName: 'Arbelaez',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOqbnhcAip7FTS4svi': 1,
      '-KgOr_at59hfkyWhxpZa': 1,
      '-KgOtIkeqwAfKNQwzzdI': 1,
      '-KgOtNDgTpPsfQ6Ky2Sn': 1,
      '-KgOuBfIhpK20jv0nbVG': 1,
      '-KkI0jYoXpkuX8fsLo7j': 1,
      '-KnqjU1dy9IMXDThy0AV': 1,
      '-Kntkq1RnIjytKrXlgVK': 1,
    },
  },
  '-KgOr9wtNW_Xj8jGiX5S': {
    active: true,
    currentMatch: '-KgOu1L99pQipAt_GPh3',
    email: 'andres.diaz@yuxiglobal.com',
    firstName: 'Andres',
    lastName: 'Diaz',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOqbnhcAip7FTS4svi': 1,
      '-KgOrMKlm7c5jmb8kuqV': 1,
      '-KgOrr4lyPlcujBvbqyv': 1,
      '-KgOtbhexS_IIXj6OfFA': 1,
      '-KgOtgQXUHets4iMU4Sr': 1,
      '-KgOwPvl_TgHRx2Oyd_r': 1,
      '-KkI17ioNADVGmtzM3aA': 1,
      '-KnuAm9FklYnq3mxwPJo': 1,
    },
  },
  '-KgOrENdp6v7JQwZSHui': {
    active: true,
    currentMatch: '-KgoUzP3-u3OEwawiIF-',
    email: 'kevin.quintero@yuxiglobal.com',
    firstName: 'Kevin',
    lastName: 'Quintero',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOqYdDS7YnTtBqzRiY': 1,
      '-KgOrr4lyPlcujBvbqyv': 1,
      '-KgOuI6H-p-sRssyGKgy': 1,
      '-KgOuvqQZdxEGBmPMrE8': 1,
      '-KgOvEluIDd1-wZKOtZY': 1,
      '-KgOvTKAaxGbU5BckZp9': 1,
      '-KgOvbJnHXFFk9IBqbSb': 1,
      '-KgPB7gJeBRm6QBmsZpN': 1,
      '-KrHzWAPpyvWkkICmtsQ': 1,
    },
  },
  '-KgOrMKlm7c5jmb8kuqV': {
    active: true,
    currentMatch: '-KgOuBfIhpK20jv0nbVG',
    email: 'veronica.lopez@yuxiglobal.com',
    firstName: 'Verónica',
    lastName: 'Lopez',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOqj7LMMxnP21GLFi3': 1,
      '-KgOr9wtNW_Xj8jGiX5S': 1,
      '-KgOrr4lyPlcujBvbqyv': 1,
      '-KgOtbhexS_IIXj6OfFA': 1,
      '-KgOvApPFJdB3FRFQF1H': 1,
      '-KgOvXhXB8MRrQXj07ee': 1,
      '-KgOvbJnHXFFk9IBqbSb': 1,
      '-KgOvyD1p2G9CUtwNKuC': 1,
      '-KgPB7gJeBRm6QBmsZpN': 1,
    },
  },
  '-KgOr_at59hfkyWhxpZa': {
    active: true,
    currentMatch: '-KgPB7gJeBRm6QBmsZpN',
    email: 'estefania.ortiz@yuxiglobal.com',
    firstName: 'Estefania',
    lastName: 'Ortiz',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOqpjLOMXrEE1d1q3C': 1,
      '-KgOr6FlNMaAa-FUEbXG': 1,
      '-KgOtIkeqwAfKNQwzzdI': 1,
      '-KgOv2t076F9-t5yU0bR': 1,
      '-KgOvApPFJdB3FRFQF1H': 1,
      '-KgOw4yHz0HwIb2SUtym': 1,
      '-KkI1Cs4vPTcRv9Xu7Y6': 1,
      '-Kpv4wFl6lcJR1G-yXvR': 1,
    },
  },
  '-KgOrheOjx6lhIMZlgOk': {
    active: true,
    currentMatch: '-KyWpcaVCYoe33f9_M2H',
    email: 'felipe.garcia@yuxiglobal.com',
    firstName: 'Felipe',
    lastName: 'Garcia',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOsjqP3zyeL9WZsBLc': 1,
      '-KgOssAtJUzn54jHBZsy': 1,
      '-KgOuZMHj59C5xujEcfv': 1,
      '-KgOukE1kQQosueoK2dI': 1,
      '-KgOuvqQZdxEGBmPMrE8': 1,
      '-KgOvApPFJdB3FRFQF1H': 1,
      '-KgOvTKAaxGbU5BckZp9': 1,
      '-KnqjDGRtKWnCh4W2_iu': 1,
    },
  },
  '-KgOrr4lyPlcujBvbqyv': {
    active: false,
    currentMatch: '',
    email: 'daniel.barrios@yuxiglobal.com',
    firstName: 'Daniel',
    lastName: 'Barrios',
    location: 1,
    matchConfirmed: false,
    matches: {
      '-KgOqtl5OarpOeSbv5L5': 1,
      '-KgOr9wtNW_Xj8jGiX5S': 1,
      '-KgOrENdp6v7JQwZSHui': 1,
      '-KgOrMKlm7c5jmb8kuqV': 1,
      '-KgOs4yXXBiQ62hBV67x': 1,
      '-KgOukE1kQQosueoK2dI': 1,
      '-KgoUVH_6okc9S8zW0vt': 1,
    },
  },
  '-KgOrwHtQzhsXiqbFYpr': {
    active: false,
    currentMatch: '',
    email: 'diana.quintero@yuxiglobal.com',
    firstName: 'Diana',
    lastName: 'Quintero',
    location: 1,
    matchConfirmed: false,
    matches: {
      '-KgOscV90waV1yADszBC': 1,
      '-KgOssAtJUzn54jHBZsy': 1,
      '-KgOtIkeqwAfKNQwzzdI': 1,
      '-KgOtbhexS_IIXj6OfFA': 1,
      '-KgOuBfIhpK20jv0nbVG': 1,
      '-KgoUaofJtY5mhveO1EH': 1,
      '-KgoX6Vglp3EXIm6aK2e': 1,
      '-KrHqEaJ5ucnyaWL5THc': 1,
    },
  },
  '-KgOs1GuireyReOzJgoN': {
    active: false,
    currentMatch: '',
    email: 'leidy.gil@yuxiglobal.com',
    firstName: 'Leidy',
    lastName: 'Gil',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOsT6XWWe3psX3Kk27': 1,
      '-KgOscV90waV1yADszBC': 1,
      '-KgOuI6H-p-sRssyGKgy': 1,
      '-KgOvEluIDd1-wZKOtZY': 1,
      '-KgoUgygaSx5P7bzYrCy': 1,
    },
  },
  '-KgOs4yXXBiQ62hBV67x': {
    active: true,
    currentMatch: '-KyWpcaMh3GmeJYZ81jV',
    email: 'juan.silva@yuxiglobal.com',
    firstName: 'Juan',
    lastName: 'Silva',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqtl5OarpOeSbv5L5': 1,
      '-KgOrr4lyPlcujBvbqyv': 1,
      '-KgOsT6XWWe3psX3Kk27': 1,
      '-KgOu88eJoXyF5dBWoUg': 1,
      '-KgOv-CH56cFUVSH2TrK': 1,
      '-KgOvrA9-7jV7c8i7Qwd': 1,
      '-KntlAGHK_u2bbmXOE0p': 1,
    },
  },
  '-KgOsT6XWWe3psX3Kk27': {
    active: true,
    currentMatch: '-KgOqbnhcAip7FTS4svi',
    email: 'fabian.buitrago@yuxiglobal.com',
    firstName: 'Fabian',
    lastName: 'Buitrago',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOs1GuireyReOzJgoN': 1,
      '-KgOs4yXXBiQ62hBV67x': 1,
      '-KgOsjqP3zyeL9WZsBLc': 1,
      '-KgOtgQXUHets4iMU4Sr': 1,
      '-KgOts51IfcFm-CG3G29': 1,
      '-KgOu1L99pQipAt_GPh3': 1,
      '-KgOukE1kQQosueoK2dI': 1,
      '-KgOwPvl_TgHRx2Oyd_r': 1,
    },
  },
  '-KgOscV90waV1yADszBC': {
    active: false,
    currentMatch: '',
    email: 'daniel.bravo@yuxiglobal.com',
    firstName: 'Daniel',
    lastName: 'Bravo',
    location: 1,
    matchConfirmed: false,
    matches: {
      '-KgOqYdDS7YnTtBqzRiY': 1,
      '-KgOrwHtQzhsXiqbFYpr': 1,
      '-KgOs1GuireyReOzJgoN': 1,
      '-KgOsxfP-fNbH_7iOO8-': 1,
      '-KgOv679TGhuCce7go8K': 1,
      '-KgOvebeq2vEcRECjba9': 1,
      '-KgoUYVSD1VZTTtvfHNp': 1,
      '-KgoUdPpKPDoTTjJVKRB': 1,
    },
  },
  '-KgOsjqP3zyeL9WZsBLc': {
    active: true,
    currentMatch: '-KkI14PCd_DplJLln3kG',
    email: 'jorge.banguera@yuxiglobal.com',
    firstName: 'Jorge',
    lastName: 'Banguera',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOrheOjx6lhIMZlgOk': 1,
      '-KgOsT6XWWe3psX3Kk27': 1,
      '-KgOssAtJUzn54jHBZsy': 1,
      '-KgOtIkeqwAfKNQwzzdI': 1,
      '-KgOv-CH56cFUVSH2TrK': 1,
      '-KgOv679TGhuCce7go8K': 1,
      '-KgOvTKAaxGbU5BckZp9': 1,
      '-KgOvkvmV9ki8L2F4wn1': 1,
      '-KnqjtRVFva3fYeSFn5G': 1,
    },
  },
  '-KgOssAtJUzn54jHBZsy': {
    active: false,
    currentMatch: '',
    email: 'esteban.santamaria@yuxiglobal.com',
    firstName: 'Esteban',
    lastName: 'Restrepo',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOrheOjx6lhIMZlgOk': 1,
      '-KgOrwHtQzhsXiqbFYpr': 1,
      '-KgOsjqP3zyeL9WZsBLc': 1,
      '-KgOtgQXUHets4iMU4Sr': 1,
      '-KgOuPDewy_QI5ReSe9e': 1,
      '-KgOwPvl_TgHRx2Oyd_r': 1,
    },
  },
  '-KgOsxfP-fNbH_7iOO8-': {
    active: false,
    currentMatch: '',
    email: 'jorge.serrano@yuxiglobal.com',
    firstName: 'Jorge',
    lastName: 'Serrano',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOqbnhcAip7FTS4svi': 1,
      '-KgOqj7LMMxnP21GLFi3': 1,
      '-KgOscV90waV1yADszBC': 1,
      '-KgOtNDgTpPsfQ6Ky2Sn': 1,
      '-KgOwSDWw8_OxrNFbRlD': 1,
      '-KgoUzP3-u3OEwawiIF-': 1,
    },
  },
  '-KgOtIkeqwAfKNQwzzdI': {
    active: true,
    currentMatch: '-KgoUpRoFhEiGVwEcxdp',
    email: 'santiago.cano@yuxiglobal.com',
    firstName: 'Santiago',
    lastName: 'Cano',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqpjLOMXrEE1d1q3C': 1,
      '-KgOr6FlNMaAa-FUEbXG': 1,
      '-KgOr_at59hfkyWhxpZa': 1,
      '-KgOrwHtQzhsXiqbFYpr': 1,
      '-KgOsjqP3zyeL9WZsBLc': 1,
      '-KgOvyD1p2G9CUtwNKuC': 1,
      '-KgoUYVSD1VZTTtvfHNp': 1,
    },
  },
  '-KgOtNDgTpPsfQ6Ky2Sn': {
    active: true,
    currentMatch: '-KyViTbDcRpQEGj7hvjB',
    email: 'julian.romero@yuxiglobal.com',
    firstName: 'Julian',
    lastName: 'Romero',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOr6FlNMaAa-FUEbXG': 1,
      '-KgOsxfP-fNbH_7iOO8-': 1,
      '-KgOtgQXUHets4iMU4Sr': 1,
      '-KgOts51IfcFm-CG3G29': 1,
      '-KgOu1L99pQipAt_GPh3': 1,
      '-KgOukE1kQQosueoK2dI': 1,
      '-KgOvApPFJdB3FRFQF1H': 1,
      '-KgOvEluIDd1-wZKOtZY': 1,
    },
  },
  '-KgOtbhexS_IIXj6OfFA': {
    active: false,
    currentMatch: '',
    email: 'felipe.jaramillo@yuxiglobal.com',
    firstName: 'Felipe',
    lastName: 'Jaramillo',
    location: 1,
    matchConfirmed: false,
    matches: {
      '-KgOqj7LMMxnP21GLFi3': 1,
      '-KgOr9wtNW_Xj8jGiX5S': 1,
      '-KgOrMKlm7c5jmb8kuqV': 1,
      '-KgOrwHtQzhsXiqbFYpr': 1,
      '-KgOvrA9-7jV7c8i7Qwd': 1,
      '-KnqjtRVFva3fYeSFn5G': 1,
      '-KrHoCXrUN_xrlXESPJs': 1,
    },
  },
  '-KgOtgQXUHets4iMU4Sr': {
    active: true,
    currentMatch: '-KyW-ShEXpwL0A6viuiD',
    email: 'yessica.gomez@yuxiglobal.com',
    firstName: 'Yessica',
    lastName: 'Gomez',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOr9wtNW_Xj8jGiX5S': 1,
      '-KgOsT6XWWe3psX3Kk27': 1,
      '-KgOssAtJUzn54jHBZsy': 1,
      '-KgOtNDgTpPsfQ6Ky2Sn': 1,
      '-KgOuBfIhpK20jv0nbVG': 1,
      '-KgOvEluIDd1-wZKOtZY': 1,
      '-KgOvbJnHXFFk9IBqbSb': 1,
      '-KgPB7gJeBRm6QBmsZpN': 1,
      '-KgoUzP3-u3OEwawiIF-': 1,
    },
  },
  '-KgOts51IfcFm-CG3G29': {
    active: true,
    currentMatch: '-KgOqj7LMMxnP21GLFi3',
    email: 'yulied.quiroz@yuxiglobal.com',
    firstName: 'Yulied',
    lastName: 'Quiroz',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOsT6XWWe3psX3Kk27': 1,
      '-KgOtNDgTpPsfQ6Ky2Sn': 1,
      '-KgOutQH_wmuaDtck1PJ': 1,
      '-KgOvEluIDd1-wZKOtZY': 1,
      '-KgOw9idQAbYbuT3k6gk': 1,
      '-KkI14PCd_DplJLln3kG': 1,
    },
  },
  '-KgOtwCHHUqbF53m_72g': {
    active: true,
    currentMatch: '-KgOvkvmV9ki8L2F4wn1',
    email: 'camila.giraldo@yuxiglobal.com',
    firstName: 'Camila',
    lastName: 'Giraldo',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqpjLOMXrEE1d1q3C': 1,
      '-KgOu88eJoXyF5dBWoUg': 1,
      '-KgOuI6H-p-sRssyGKgy': 1,
      '-KgOv2t076F9-t5yU0bR': 1,
      '-KgoUVH_6okc9S8zW0vt': 1,
      '-KgoUpRoFhEiGVwEcxdp': 1,
      '-KnqjpHTvwRGKREmTSFk': 1,
    },
  },
  '-KgOu1L99pQipAt_GPh3': {
    active: true,
    currentMatch: '-KgOr9wtNW_Xj8jGiX5S',
    email: 'sandra.giraldo@yuxiglobal.com',
    firstName: 'Sandra',
    lastName: 'Giraldo',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOqpjLOMXrEE1d1q3C': 1,
      '-KgOsT6XWWe3psX3Kk27': 1,
      '-KgOtNDgTpPsfQ6Ky2Sn': 1,
      '-KgoX6Vglp3EXIm6aK2e': 1,
      '-KkI0jYoXpkuX8fsLo7j': 1,
    },
  },
  '-KgOu88eJoXyF5dBWoUg': {
    active: true,
    currentMatch: '-KgOvyD1p2G9CUtwNKuC',
    email: 'fred.pizarro@yuxiglobal.com',
    firstName: 'Fred',
    lastName: 'Pizarro',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOs4yXXBiQ62hBV67x': 1,
      '-KgOtwCHHUqbF53m_72g': 1,
      '-KgOvvDPKyYoW8JVAMmo': 1,
      '-KgOw4yHz0HwIb2SUtym': 1,
      '-KgoUgygaSx5P7bzYrCy': 1,
      '-KgoUpRoFhEiGVwEcxdp': 1,
      '-Kntkq1RnIjytKrXlgVK': 1,
    },
  },
  '-KgOuBfIhpK20jv0nbVG': {
    active: true,
    currentMatch: '-KgOrMKlm7c5jmb8kuqV',
    email: 'armando.restrepo@yuxiglobal.com',
    firstName: 'Armando',
    lastName: 'Restrepo',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOr6FlNMaAa-FUEbXG': 1,
      '-KgOrwHtQzhsXiqbFYpr': 1,
      '-KgOtgQXUHets4iMU4Sr': 1,
      '-KgOukE1kQQosueoK2dI': 1,
      '-KgOvebeq2vEcRECjba9': 1,
      '-KkI1AO_n-QalxoN8agc': 1,
    },
  },
  '-KgOuI6H-p-sRssyGKgy': {
    active: true,
    currentMatch: '-KntlAGHK_u2bbmXOE0p',
    email: 'juan.hernandez@yuxiglobal.com',
    firstName: 'Juan',
    lastName: 'Hernandez',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqbnhcAip7FTS4svi': 1,
      '-KgOrENdp6v7JQwZSHui': 1,
      '-KgOs1GuireyReOzJgoN': 1,
      '-KgOtwCHHUqbF53m_72g': 1,
      '-KgOuPDewy_QI5ReSe9e': 1,
      '-KgOuotfdOsLHVs2jffl': 1,
    },
  },
  '-KgOuMLXIyusolWaVklf': {
    active: false,
    currentMatch: '',
    email: 'camilo.villa@yuxiglobal.com',
    firstName: 'Camilo',
    lastName: 'Villa',
    location: 0,
    matchConfirmed: false,
    matches: { '-KgOuvqQZdxEGBmPMrE8': 1, '-KgOvXhXB8MRrQXj07ee': 1 },
  },
  '-KgOuPDewy_QI5ReSe9e': {
    active: true,
    currentMatch: '-KgoUmHRnLryFRVPkMET',
    email: 'maria.llano@yuxiglobal.com',
    firstName: 'Maria',
    lastName: 'Llano',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOssAtJUzn54jHBZsy': 1,
      '-KgOuI6H-p-sRssyGKgy': 1,
      '-KgOukE1kQQosueoK2dI': 1,
      '-KgOvkvmV9ki8L2F4wn1': 1,
      '-KgOvyD1p2G9CUtwNKuC': 1,
      '-Knqk34FoGzjT5ubSfG2': 1,
    },
  },
  '-KgOuZMHj59C5xujEcfv': {
    active: true,
    currentMatch: '-KgoV2LAGzt1LCVFbPfT',
    email: 'eliana.caraballo@yuxiglobal.com',
    firstName: 'Eliana',
    lastName: 'Caraballo',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOqj7LMMxnP21GLFi3': 1,
      '-KgOrheOjx6lhIMZlgOk': 1,
      '-KgOvo9X5Ofa120BmH3y': 1,
      '-KgPB7gJeBRm6QBmsZpN': 1,
      '-KgoUVH_6okc9S8zW0vt': 1,
      '-Kntmfcpd7627UdsUoUh': 1,
    },
  },
  '-KgOukE1kQQosueoK2dI': {
    active: true,
    currentMatch: '-KgOvApPFJdB3FRFQF1H',
    email: 'claudia.ariza@yuxiglobal.com',
    firstName: 'Claudia',
    lastName: 'Ariza',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOrheOjx6lhIMZlgOk': 1,
      '-KgOrr4lyPlcujBvbqyv': 1,
      '-KgOsT6XWWe3psX3Kk27': 1,
      '-KgOtNDgTpPsfQ6Ky2Sn': 1,
      '-KgOuBfIhpK20jv0nbVG': 1,
      '-KgOuPDewy_QI5ReSe9e': 1,
    },
  },
  '-KgOuotfdOsLHVs2jffl': {
    active: true,
    currentMatch: '-KrHzWAPpyvWkkICmtsQ',
    email: 'alejandro.lopez@yuxiglobal.com',
    firstName: 'Alejandro',
    lastName: 'Lopez',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqtl5OarpOeSbv5L5': 1,
      '-KgOuI6H-p-sRssyGKgy': 1,
      '-KgOvEluIDd1-wZKOtZY': 1,
      '-KgOvo9X5Ofa120BmH3y': 1,
      '-KnqjDGRtKWnCh4W2_iu': 1,
      '-KntlAGHK_u2bbmXOE0p': 1,
    },
  },
  '-KgOutQH_wmuaDtck1PJ': {
    active: false,
    currentMatch: '',
    email: 'juan.gaviria@yuxiglobal.com',
    firstName: 'Juan',
    lastName: 'Gaviria',
    location: 2,
    matchConfirmed: false,
    matches: { '-KgOts51IfcFm-CG3G29': 1, '-KgoUjpgPCFPUa6JB8GL': 1 },
  },
  '-KgOuvqQZdxEGBmPMrE8': {
    active: false,
    currentMatch: '',
    email: 'sandra.rios@yuxiglobal.com',
    firstName: 'Sandra',
    lastName: 'Rios',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOrENdp6v7JQwZSHui': 1,
      '-KgOrheOjx6lhIMZlgOk': 1,
      '-KgOuMLXIyusolWaVklf': 1,
    },
  },
  '-KgOv-CH56cFUVSH2TrK': {
    active: true,
    currentMatch: '-KkI17ioNADVGmtzM3aA',
    email: 'ayrton.rojo@yuxiglobal.com',
    firstName: 'Ayrton',
    lastName: 'Rojo',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqbnhcAip7FTS4svi': 1,
      '-KgOs4yXXBiQ62hBV67x': 1,
      '-KgOsjqP3zyeL9WZsBLc': 1,
      '-KgOv679TGhuCce7go8K': 1,
      '-KgOvo9X5Ofa120BmH3y': 1,
      '-KgoUgygaSx5P7bzYrCy': 1,
    },
  },
  '-KgOv2t076F9-t5yU0bR': {
    active: true,
    currentMatch: '-Knqk34FoGzjT5ubSfG2',
    email: 'marcos.arenas@yuxiglobal.com',
    firstName: 'Marcos',
    lastName: 'Arenas',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqYdDS7YnTtBqzRiY': 1,
      '-KgOr_at59hfkyWhxpZa': 1,
      '-KgOtwCHHUqbF53m_72g': 1,
      '-KgOvo9X5Ofa120BmH3y': 1,
      '-KgoUaofJtY5mhveO1EH': 1,
      '-KpvFJ1KVITVz2dtcQj0': 1,
    },
  },
  '-KgOv679TGhuCce7go8K': {
    active: false,
    currentMatch: '',
    email: 'jorge.buendia@yuxiglobal.com',
    firstName: 'Jorge',
    lastName: 'Buendia',
    location: 1,
    matchConfirmed: false,
    matches: {
      '-KgOqj7LMMxnP21GLFi3': 1,
      '-KgOscV90waV1yADszBC': 1,
      '-KgOsjqP3zyeL9WZsBLc': 1,
      '-KgOv-CH56cFUVSH2TrK': 1,
      '-KgOvvDPKyYoW8JVAMmo': 1,
      '-KgoUzP3-u3OEwawiIF-': 1,
    },
  },
  '-KgOvApPFJdB3FRFQF1H': {
    active: true,
    currentMatch: '-KgOukE1kQQosueoK2dI',
    email: 'mateo.castano@yuxiglobal.com',
    firstName: 'Mateo',
    lastName: 'Castaño',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOqbnhcAip7FTS4svi': 1,
      '-KgOrMKlm7c5jmb8kuqV': 1,
      '-KgOr_at59hfkyWhxpZa': 1,
      '-KgOrheOjx6lhIMZlgOk': 1,
      '-KgOtNDgTpPsfQ6Ky2Sn': 1,
      '-KnqjpHTvwRGKREmTSFk': 1,
    },
  },
  '-KgOvEluIDd1-wZKOtZY': {
    active: true,
    currentMatch: '-KkI1AO_n-QalxoN8agc',
    email: 'esteban.arango@yuxiglobal.com',
    firstName: 'Esteban',
    lastName: 'Arango',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOrENdp6v7JQwZSHui': 1,
      '-KgOs1GuireyReOzJgoN': 1,
      '-KgOtNDgTpPsfQ6Ky2Sn': 1,
      '-KgOtgQXUHets4iMU4Sr': 1,
      '-KgOts51IfcFm-CG3G29': 1,
      '-KgOuotfdOsLHVs2jffl': 1,
    },
  },
  '-KgOvTKAaxGbU5BckZp9': {
    active: false,
    currentMatch: '',
    email: 'angela.ordonez@yuxiglobal.com',
    firstName: 'Angela',
    lastName: 'Ordoñez',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOrENdp6v7JQwZSHui': 1,
      '-KgOrheOjx6lhIMZlgOk': 1,
      '-KgOsjqP3zyeL9WZsBLc': 1,
      '-KkI0jYoXpkuX8fsLo7j': 1,
      '-KrHqL4HSH5tdbyh8ahe': 1,
    },
  },
  '-KgOvXhXB8MRrQXj07ee': {
    active: true,
    currentMatch: '-Kntmfcpd7627UdsUoUh',
    email: 'jorge.hurtado@yuxiglobal.com',
    firstName: 'Jorge',
    lastName: 'Hurtado',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOrMKlm7c5jmb8kuqV': 1,
      '-KgOuMLXIyusolWaVklf': 1,
      '-KgOwPvl_TgHRx2Oyd_r': 1,
      '-KgoUjpgPCFPUa6JB8GL': 1,
      '-KkI17ioNADVGmtzM3aA': 1,
      '-KrHqYQIRS9X-cRkrhaj': 1,
    },
  },
  '-KgOvbJnHXFFk9IBqbSb': {
    active: true,
    currentMatch: '-KyViTbBnDSNL-N4WTEq',
    email: 'daniel.florez@yuxiglobal.com',
    firstName: 'Daniel',
    lastName: 'Florez',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOqpjLOMXrEE1d1q3C': 1,
      '-KgOrENdp6v7JQwZSHui': 1,
      '-KgOrMKlm7c5jmb8kuqV': 1,
      '-KgOtgQXUHets4iMU4Sr': 1,
      '-KkI0jYoXpkuX8fsLo7j': 1,
      '-Knqk34FoGzjT5ubSfG2': 1,
    },
  },
  '-KgOvebeq2vEcRECjba9': {
    active: true,
    currentMatch: '-KyViTbBnDSNL-N4WTEr',
    email: 'natalia.mejia@yuxiglobal.com',
    firstName: 'Natalia',
    lastName: 'Mejia',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqpjLOMXrEE1d1q3C': 1,
      '-KgOscV90waV1yADszBC': 1,
      '-KgOuBfIhpK20jv0nbVG': 1,
      '-KgOw4yHz0HwIb2SUtym': 1,
      '-KgPB7gJeBRm6QBmsZpN': 1,
      '-KnqjpHTvwRGKREmTSFk': 1,
    },
  },
  '-KgOvkvmV9ki8L2F4wn1': {
    active: true,
    currentMatch: '-KgOtwCHHUqbF53m_72g',
    email: 'carlos.carrero@yuxiglobal.com',
    firstName: 'Carlos',
    lastName: 'Carrero',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqbnhcAip7FTS4svi': 1,
      '-KgOqj7LMMxnP21GLFi3': 1,
      '-KgOsjqP3zyeL9WZsBLc': 1,
      '-KgOuPDewy_QI5ReSe9e': 1,
      '-KgOw1jekIf09IoMvPEu': 1,
      '-KnqjjFW6li72-Q_zLrS': 1,
    },
  },
  '-KgOvo9X5Ofa120BmH3y': {
    active: true,
    currentMatch: '-KyW-ShIo7R-JN68ZUOU',
    email: 'roger.alvarez@yuxiglobal.com',
    firstName: 'Roger',
    lastName: 'Alvarez',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOuZMHj59C5xujEcfv': 1,
      '-KgOuotfdOsLHVs2jffl': 1,
      '-KgOv-CH56cFUVSH2TrK': 1,
      '-KgOv2t076F9-t5yU0bR': 1,
      '-KnqjjFW6li72-Q_zLrS': 1,
    },
  },
  '-KgOvrA9-7jV7c8i7Qwd': {
    active: true,
    currentMatch: '-KyWpcaQvrfDJHEQxltG',
    email: 'luisa.arias@yuxiglobal.com',
    firstName: 'Luisa',
    lastName: 'Arias',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOs4yXXBiQ62hBV67x': 1,
      '-KgOtbhexS_IIXj6OfFA': 1,
      '-KgoUmHRnLryFRVPkMET': 1,
      '-KkI1AO_n-QalxoN8agc': 1,
      '-KrHoccRzXt7n62m4J5t': 1,
    },
  },
  '-KgOvvDPKyYoW8JVAMmo': {
    active: false,
    currentMatch: '',
    email: 'andres.sierra@yuxiglobal.com',
    firstName: 'Andres',
    lastName: 'Sierra',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgOu88eJoXyF5dBWoUg': 1, '-KgOv679TGhuCce7go8K': 1 },
  },
  '-KgOvyD1p2G9CUtwNKuC': {
    active: true,
    currentMatch: '-KgOu88eJoXyF5dBWoUg',
    email: 'pablo.diaz@yuxiglobal.com',
    firstName: 'Pablo',
    lastName: 'Diaz',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOrMKlm7c5jmb8kuqV': 1,
      '-KgOtIkeqwAfKNQwzzdI': 1,
      '-KgOuPDewy_QI5ReSe9e': 1,
      '-KgoUYVSD1VZTTtvfHNp': 1,
      '-KkI1AO_n-QalxoN8agc': 1,
    },
  },
  '-KgOw1jekIf09IoMvPEu': {
    active: false,
    currentMatch: '',
    email: 'alejandra.marulanda@yuxiglobal.com',
    firstName: 'Alejandra',
    lastName: 'Marulanda',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgOqbnhcAip7FTS4svi': 1, '-KgOvkvmV9ki8L2F4wn1': 1 },
  },
  '-KgOw4yHz0HwIb2SUtym': {
    active: false,
    currentMatch: '',
    email: 'harlen.giraldo@yuxiglobal.com',
    firstName: 'Harlen',
    lastName: 'Giraldo',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOr_at59hfkyWhxpZa': 1,
      '-KgOu88eJoXyF5dBWoUg': 1,
      '-KgOvebeq2vEcRECjba9': 1,
      '-KpvFJ1KVITVz2dtcQj0': 1,
      '-KrHqdqMcrmoh0vYcmli': 1,
    },
  },
  '-KgOw9idQAbYbuT3k6gk': {
    active: true,
    currentMatch: '-KyWpcaSt2iwMuN0EMAh',
    email: 'christian.villa@yuxiglobal.com',
    firstName: 'Christian',
    lastName: 'Villa',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOqYdDS7YnTtBqzRiY': 1,
      '-KgOts51IfcFm-CG3G29': 1,
      '-KgOwPvl_TgHRx2Oyd_r': 1,
      '-KgoV2LAGzt1LCVFbPfT': 1,
      '-KnqjyPcpP6g5m7nJxTO': 1,
    },
  },
  '-KgOwPvl_TgHRx2Oyd_r': {
    active: true,
    currentMatch: '-KyWpcaU1xxfiWz8Ur8P',
    email: 'gloriia04@hotmail.com',
    firstName: 'Gloria',
    lastName: 'Vanegas',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOr9wtNW_Xj8jGiX5S': 1,
      '-KgOsT6XWWe3psX3Kk27': 1,
      '-KgOssAtJUzn54jHBZsy': 1,
      '-KgOvXhXB8MRrQXj07ee': 1,
      '-KgOw9idQAbYbuT3k6gk': 1,
    },
  },
  '-KgOwSDWw8_OxrNFbRlD': {
    active: true,
    currentMatch: '-KyViTbDcRpQEGj7hvjC',
    email: 'olga8ac@hotmail.com',
    firstName: 'Olga',
    lastName: 'Ochoa',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOqpjLOMXrEE1d1q3C': 1,
      '-KgOsxfP-fNbH_7iOO8-': 1,
      '-KgoUmHRnLryFRVPkMET': 1,
      '-KgoUzP3-u3OEwawiIF-': 1,
      '-KgoV2LAGzt1LCVFbPfT': 1,
    },
  },
  '-KgPB7gJeBRm6QBmsZpN': {
    active: true,
    currentMatch: '-KgOr_at59hfkyWhxpZa',
    email: 'juan.herrera@yuxiglobal.com',
    firstName: 'Juan',
    lastName: 'Herrera',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOrENdp6v7JQwZSHui': 1,
      '-KgOrMKlm7c5jmb8kuqV': 1,
      '-KgOtgQXUHets4iMU4Sr': 1,
      '-KgOuZMHj59C5xujEcfv': 1,
      '-KgOvebeq2vEcRECjba9': 1,
      '-KgoUYVSD1VZTTtvfHNp': 1,
      '-KkI17ioNADVGmtzM3aA': 1,
      '-Knqk34FoGzjT5ubSfG2': 1,
      '-KrHq0DNPuovXJdNzCrB': 1,
    },
  },
  '-KgoUVH_6okc9S8zW0vt': {
    active: true,
    currentMatch: '-KgoUgygaSx5P7bzYrCy',
    email: 'james.santoya@yuxiglobal.com',
    firstName: 'James',
    lastName: 'Santoya',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOrr4lyPlcujBvbqyv': 1,
      '-KgOtwCHHUqbF53m_72g': 1,
      '-KgOuZMHj59C5xujEcfv': 1,
      '-KgoUweZywNFSY4NulCB': 1,
      '-KrHq7hCrpDOJYl0Uhsa': 1,
    },
  },
  '-KgoUYVSD1VZTTtvfHNp': {
    active: true,
    currentMatch: '-KyWpcaWs6CKLSM6PeDY',
    email: 'laura.ciro@yuxiglobal.com',
    firstName: 'Laura',
    lastName: 'Ciro',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOscV90waV1yADszBC': 1,
      '-KgOtIkeqwAfKNQwzzdI': 1,
      '-KgOvyD1p2G9CUtwNKuC': 1,
      '-KgPB7gJeBRm6QBmsZpN': 1,
      '-KgoUgygaSx5P7bzYrCy': 1,
    },
  },
  '-KgoUaofJtY5mhveO1EH': {
    active: false,
    currentMatch: '',
    email: 'johan.quintana@yuxiglobal.com',
    firstName: 'Johan',
    lastName: 'Quintana',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOqj7LMMxnP21GLFi3': 1,
      '-KgOrwHtQzhsXiqbFYpr': 1,
      '-KgOv2t076F9-t5yU0bR': 1,
      '-KgoUmHRnLryFRVPkMET': 1,
      '-KkI1AO_n-QalxoN8agc': 1,
    },
  },
  '-KgoUdPpKPDoTTjJVKRB': {
    active: false,
    currentMatch: '',
    email: 'cesar.balcazar@yuxiglobal.com',
    firstName: 'Cesar',
    lastName: 'Balcazar',
    location: 2,
    matchConfirmed: false,
    matches: { '-KgOscV90waV1yADszBC': 1, '-KgoUzP3-u3OEwawiIF-': 1 },
  },
  '-KgoUgygaSx5P7bzYrCy': {
    active: true,
    currentMatch: '-KgoUVH_6okc9S8zW0vt',
    email: 'andres.hurtado@yuxiglobal.com',
    firstName: 'Andres',
    lastName: 'Hurtado',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOs1GuireyReOzJgoN': 1,
      '-KgOu88eJoXyF5dBWoUg': 1,
      '-KgOv-CH56cFUVSH2TrK': 1,
      '-KgoUYVSD1VZTTtvfHNp': 1,
      '-KgoUpRoFhEiGVwEcxdp': 1,
    },
  },
  '-KgoUjpgPCFPUa6JB8GL': {
    active: false,
    currentMatch: '',
    email: 'renata.aguilar@yuxiglobal.com',
    firstName: 'Renata',
    lastName: 'Aguilar',
    location: 0,
    matchConfirmed: false,
    matches: {
      '-KgOutQH_wmuaDtck1PJ': 1,
      '-KgOvXhXB8MRrQXj07ee': 1,
      '-KgoV2LAGzt1LCVFbPfT': 1,
    },
  },
  '-KgoUmHRnLryFRVPkMET': {
    active: true,
    currentMatch: '-KgOuPDewy_QI5ReSe9e',
    email: 'juan.rendon@yuxiglobal.com',
    firstName: 'Juan',
    lastName: 'Rendon',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOvrA9-7jV7c8i7Qwd': 1,
      '-KgOwSDWw8_OxrNFbRlD': 1,
      '-KgoUaofJtY5mhveO1EH': 1,
      '-KkI1Cs4vPTcRv9Xu7Y6': 1,
      '-KnqjyPcpP6g5m7nJxTO': 1,
    },
  },
  '-KgoUpRoFhEiGVwEcxdp': {
    active: true,
    currentMatch: '-KgOtIkeqwAfKNQwzzdI',
    email: 'juan.villa@yuxiglobal.com',
    firstName: 'Juan',
    lastName: 'Villa',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOtwCHHUqbF53m_72g': 1,
      '-KgOu88eJoXyF5dBWoUg': 1,
      '-KgoUgygaSx5P7bzYrCy': 1,
      '-KgoX6Vglp3EXIm6aK2e': 1,
      '-KrW2Ye5CaU0_8s2YgaP': 1,
    },
  },
  '-KgoUweZywNFSY4NulCB': {
    active: false,
    currentMatch: '',
    email: 'juliana.aristizabal@yuxiglobal.com',
    firstName: 'Juliana',
    lastName: 'Aristizabal',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgoUVH_6okc9S8zW0vt': 1 },
  },
  '-KgoUzP3-u3OEwawiIF-': {
    active: true,
    currentMatch: '-KgOrENdp6v7JQwZSHui',
    email: 'andres.espino@yuxiglobal.com',
    firstName: 'Andres',
    lastName: 'Espino',
    location: 2,
    matchConfirmed: true,
    matches: {
      '-KgOsxfP-fNbH_7iOO8-': 1,
      '-KgOtgQXUHets4iMU4Sr': 1,
      '-KgOv679TGhuCce7go8K': 1,
      '-KgOwSDWw8_OxrNFbRlD': 1,
      '-KgoUdPpKPDoTTjJVKRB': 1,
    },
  },
  '-KgoV2LAGzt1LCVFbPfT': {
    active: true,
    currentMatch: '-KgOuZMHj59C5xujEcfv',
    email: 'camilo.velez@yuxiglobal.com',
    firstName: 'Camilo',
    lastName: 'Velez',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOw9idQAbYbuT3k6gk': 1,
      '-KgOwSDWw8_OxrNFbRlD': 1,
      '-KgoUjpgPCFPUa6JB8GL': 1,
      '-KnqjyPcpP6g5m7nJxTO': 1,
      '-Kntmfcpd7627UdsUoUh': 1,
    },
  },
  '-KgoX6Vglp3EXIm6aK2e': {
    active: false,
    currentMatch: '',
    email: 'alejandro.sanchez@yuxiglobal.com',
    firstName: 'Alejandro',
    lastName: 'Sanchez',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOrwHtQzhsXiqbFYpr': 1,
      '-KgOu1L99pQipAt_GPh3': 1,
      '-KgoUpRoFhEiGVwEcxdp': 1,
    },
  },
  '-KkI0jYoXpkuX8fsLo7j': {
    active: true,
    currentMatch: '-KyWpcaTm0Pw2cJCAGrf',
    email: 'cristian.ortiz@yuxiglobal.com',
    firstName: 'Cristian',
    lastName: 'Ortiz',
    location: 0,
    matchConfirmed: true,
    matches: {
      '-KgOr6FlNMaAa-FUEbXG': 1,
      '-KgOu1L99pQipAt_GPh3': 1,
      '-KgOvTKAaxGbU5BckZp9': 1,
      '-KgOvbJnHXFFk9IBqbSb': 1,
    },
  },
  '-KkI14PCd_DplJLln3kG': {
    active: true,
    currentMatch: '-KgOsjqP3zyeL9WZsBLc',
    email: 'mateo.parra@yuxiglobal.com',
    firstName: 'Mateo',
    lastName: 'Parra',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOts51IfcFm-CG3G29': 1,
      '-KkI17ioNADVGmtzM3aA': 1,
      '-KnqjU1dy9IMXDThy0AV': 1,
      '-KrHoLVoGwtJqX523n2q': 1,
    },
  },
  '-KkI17ioNADVGmtzM3aA': {
    active: true,
    currentMatch: '-KgOv-CH56cFUVSH2TrK',
    email: 'lina.colorado@yuxiglobal.com',
    firstName: 'Lina',
    lastName: 'Colorado',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOr9wtNW_Xj8jGiX5S': 1,
      '-KgOvXhXB8MRrQXj07ee': 1,
      '-KgPB7gJeBRm6QBmsZpN': 1,
      '-KkI14PCd_DplJLln3kG': 1,
    },
  },
  '-KkI1AO_n-QalxoN8agc': {
    active: true,
    currentMatch: '-KgOvEluIDd1-wZKOtZY',
    email: 'luz.berrio@yuxiglobal.com',
    firstName: 'Luz',
    lastName: 'Berrio',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOuBfIhpK20jv0nbVG': 1,
      '-KgOvrA9-7jV7c8i7Qwd': 1,
      '-KgOvyD1p2G9CUtwNKuC': 1,
      '-KgoUaofJtY5mhveO1EH': 1,
    },
  },
  '-KkI1Cs4vPTcRv9Xu7Y6': {
    active: true,
    currentMatch: '-KrHqdqMcrmoh0vYcmli',
    email: 'leonardo.perez@yuxiglobal.com',
    firstName: 'Leonardo',
    lastName: 'Perez',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOr_at59hfkyWhxpZa': 1,
      '-KgoUmHRnLryFRVPkMET': 1,
      '-KnqjjFW6li72-Q_zLrS': 1,
      '-Kntkq1RnIjytKrXlgVK': 1,
    },
  },
  '-KnqjDGRtKWnCh4W2_iu': {
    active: false,
    currentMatch: '',
    email: 'leidy.delgado@yuxiglobal.com',
    firstName: 'Leidy',
    lastName: 'Delgado',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOrheOjx6lhIMZlgOk': 1,
      '-KgOuotfdOsLHVs2jffl': 1,
      '-KnqjbyCC6unl6xowIA1': 1,
    },
  },
  '-KnqjU1dy9IMXDThy0AV': {
    active: false,
    currentMatch: '',
    email: 'leidy.zapata@yuxiglobal.com',
    firstName: 'Leidy',
    lastName: 'Zapata',
    location: 1,
    matchConfirmed: false,
    matches: {
      '-KgOr6FlNMaAa-FUEbXG': 1,
      '-KkI14PCd_DplJLln3kG': 1,
      '-KnqjbyCC6unl6xowIA1': 1,
    },
  },
  '-KnqjbyCC6unl6xowIA1': {
    active: true,
    currentMatch: '-KyViTb9C6y5gRhBxAj1',
    email: 'hernan.sanchez@yuxiglobal.com',
    firstName: 'Hernan',
    lastName: 'Sanchez',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KnqjDGRtKWnCh4W2_iu': 1,
      '-KnqjU1dy9IMXDThy0AV': 1,
      '-Kpv4wFl6lcJR1G-yXvR': 1,
    },
  },
  '-KnqjjFW6li72-Q_zLrS': {
    active: true,
    currentMatch: '-KyWpcaROWIviAHeIRyx',
    email: 'johana.medina@yuxiglobal.com',
    firstName: 'Johana',
    lastName: 'Medina',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOvkvmV9ki8L2F4wn1': 1,
      '-KgOvo9X5Ofa120BmH3y': 1,
      '-KkI1Cs4vPTcRv9Xu7Y6': 1,
    },
  },
  '-KnqjpHTvwRGKREmTSFk': {
    active: true,
    currentMatch: '-KnqjtRVFva3fYeSFn5G',
    email: 'cesar.duque@yuxiglobal.com',
    firstName: 'Cesar',
    lastName: 'Duque',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOtwCHHUqbF53m_72g': 1,
      '-KgOvApPFJdB3FRFQF1H': 1,
      '-KgOvebeq2vEcRECjba9': 1,
    },
  },
  '-KnqjtRVFva3fYeSFn5G': {
    active: true,
    currentMatch: '-KnqjpHTvwRGKREmTSFk',
    email: 'osman.hoyos@yuxiglobal.com',
    firstName: 'Osman',
    lastName: 'Hoyos',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqpjLOMXrEE1d1q3C': 1,
      '-KgOsjqP3zyeL9WZsBLc': 1,
      '-KgOtbhexS_IIXj6OfFA': 1,
    },
  },
  '-KnqjyPcpP6g5m7nJxTO': {
    active: false,
    currentMatch: '',
    email: 'isabel.guzman@yuxiglobal.com',
    firstName: 'Isabel',
    lastName: 'Guzman',
    location: 2,
    matchConfirmed: false,
    matches: {
      '-KgOw9idQAbYbuT3k6gk': 1,
      '-KgoUmHRnLryFRVPkMET': 1,
      '-KgoV2LAGzt1LCVFbPfT': 1,
    },
  },
  '-Knqk34FoGzjT5ubSfG2': {
    active: true,
    currentMatch: '-KgOv2t076F9-t5yU0bR',
    email: 'eliana.lopez@yuxiglobal.com',
    firstName: 'Eliana',
    lastName: 'López',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOuPDewy_QI5ReSe9e': 1,
      '-KgOvbJnHXFFk9IBqbSb': 1,
      '-KgPB7gJeBRm6QBmsZpN': 1,
    },
  },
  '-Kntkq1RnIjytKrXlgVK': {
    active: false,
    currentMatch: '',
    email: 'marly.arango@yuxiglobal.com',
    firstName: 'Marly',
    lastName: 'Arango',
    location: 1,
    matchConfirmed: false,
    matches: {
      '-KgOr6FlNMaAa-FUEbXG': 1,
      '-KgOu88eJoXyF5dBWoUg': 1,
      '-KkI1Cs4vPTcRv9Xu7Y6': 1,
    },
  },
  '-KntlAGHK_u2bbmXOE0p': {
    active: true,
    currentMatch: '-KgOuI6H-p-sRssyGKgy',
    email: 'maria.cardenas@yuxiglobal.com',
    firstName: 'Maria',
    lastName: 'Cardenas',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOs4yXXBiQ62hBV67x': 1,
      '-KgOuotfdOsLHVs2jffl': 1,
      '-KnuAm9FklYnq3mxwPJo': 1,
    },
  },
  '-Kntmfcpd7627UdsUoUh': {
    active: true,
    currentMatch: '-KgOvXhXB8MRrQXj07ee',
    email: 'juan.pulido@yuxiglobal.com',
    firstName: 'Juan',
    lastName: 'Pulido',
    location: 1,
    matchConfirmed: true,
    matches: {
      '-KgOqj7LMMxnP21GLFi3': 1,
      '-KgOuZMHj59C5xujEcfv': 1,
      '-KgoV2LAGzt1LCVFbPfT': 1,
    },
  },
  '-KnuAm9FklYnq3mxwPJo': {
    active: false,
    currentMatch: '',
    email: 'gerardo.calvo@yuxiglobal.com',
    firstName: 'Gerardo',
    lastName: 'Calvo',
    location: 2,
    matchConfirmed: false,
    matches: { '-KgOr9wtNW_Xj8jGiX5S': 1, '-KntlAGHK_u2bbmXOE0p': 1 },
  },
  '-Kpv4wFl6lcJR1G-yXvR': {
    active: false,
    currentMatch: '',
    email: 'victor@globalperformancesearch.com',
    firstName: 'Victor',
    lastName: 'Florez',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgOr_at59hfkyWhxpZa': 1, '-KnqjbyCC6unl6xowIA1': 1 },
  },
  '-KpvFJ1KVITVz2dtcQj0': {
    active: true,
    currentMatch: '-KrHqrY1u2GdAl8ut7WV',
    email: 'andres.echeverri@yuxiglobal.com',
    firstName: 'Andres',
    lastName: 'Echeverri',
    location: 1,
    matchConfirmed: true,
    matches: { '-KgOv2t076F9-t5yU0bR': 1, '-KgOw4yHz0HwIb2SUtym': 1 },
  },
  '-KrHoCXrUN_xrlXESPJs': {
    active: false,
    currentMatch: '',
    email: 'heider.llanten@yuxiglobal.com',
    firstName: 'Heider',
    lastName: 'Llanten',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgOtbhexS_IIXj6OfFA': 1 },
  },
  '-KrHoLVoGwtJqX523n2q': {
    active: false,
    currentMatch: '',
    email: 'mauricio.panesso@yuxiglobal.com',
    firstName: 'Mauricio',
    lastName: 'Arroyave',
    location: 1,
    matchConfirmed: false,
    matches: { '-KkI14PCd_DplJLln3kG': 1 },
  },
  '-KrHoccRzXt7n62m4J5t': {
    active: false,
    currentMatch: '',
    email: 'daniel.henao@yuxiglobal.com',
    firstName: 'Daniel',
    lastName: 'Henao',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgOvrA9-7jV7c8i7Qwd': 1 },
  },
  '-KrHq0DNPuovXJdNzCrB': {
    active: false,
    currentMatch: '',
    email: 'juan.alzate@yuxiglobal.com',
    firstName: 'Juan',
    lastName: 'Alzate',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgPB7gJeBRm6QBmsZpN': 1 },
  },
  '-KrHq7hCrpDOJYl0Uhsa': {
    active: false,
    currentMatch: '',
    email: 'juan.cardona@yuxiglobal.com',
    firstName: 'Sebastian',
    lastName: 'Cardona',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgoUVH_6okc9S8zW0vt': 1 },
  },
  '-KrHqEaJ5ucnyaWL5THc': {
    active: false,
    currentMatch: '',
    email: 'johanns.villa@yuxiglobal.com',
    firstName: 'Jhohanns',
    lastName: 'Villa',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgOrwHtQzhsXiqbFYpr': 1 },
  },
  '-KrHqL4HSH5tdbyh8ahe': {
    active: false,
    currentMatch: '',
    email: 'brian.tafur@yuxiglobal.com',
    firstName: 'Brian',
    lastName: 'Tafur',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgOvTKAaxGbU5BckZp9': 1 },
  },
  '-KrHqYQIRS9X-cRkrhaj': {
    active: false,
    currentMatch: '',
    email: 'brayan.giraldo@yuxiglobal.com',
    firstName: 'Brayan',
    lastName: 'Giraldo',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgOvXhXB8MRrQXj07ee': 1 },
  },
  '-KrHqdqMcrmoh0vYcmli': {
    active: true,
    currentMatch: '-KkI1Cs4vPTcRv9Xu7Y6',
    email: 'ana.sanchez@yuxiglobal.com',
    firstName: 'Ana',
    lastName: 'Sanchez',
    location: 1,
    matchConfirmed: true,
    matches: { '-KgOw4yHz0HwIb2SUtym': 1 },
  },
  '-KrHqrY1u2GdAl8ut7WV': {
    active: true,
    currentMatch: '-KpvFJ1KVITVz2dtcQj0',
    email: 'diego.delgado@yuxiglobal.com',
    firstName: 'Diego',
    lastName: 'Delgado',
    location: 1,
    matchConfirmed: true,
    matches: { '-KgOqbnhcAip7FTS4svi': 1 },
  },
  '-KrHzWAPpyvWkkICmtsQ': {
    active: true,
    currentMatch: '-KgOuotfdOsLHVs2jffl',
    email: 'milena.mora@yuxiglobal.com',
    firstName: 'Milena',
    lastName: 'Mora',
    location: 1,
    matchConfirmed: true,
    matches: { '-KgOrENdp6v7JQwZSHui': 1 },
  },
  '-KrW2Ye5CaU0_8s2YgaP': {
    active: false,
    currentMatch: '',
    email: 'miguel.tamayo@yuxiglobal.com',
    firstName: 'Miguel',
    lastName: 'Tamayo',
    location: 1,
    matchConfirmed: false,
    matches: { '-KgoUpRoFhEiGVwEcxdp': 1 },
  },
  '-KyViTb9C6y5gRhBxAj1': {
    active: true,
    currentMatch: '-KnqjbyCC6unl6xowIA1',
    email: 'silvana.perez@yuxiglobal.com',
    firstName: 'Silvana',
    lastName: 'Perez',
    location: 1,
    matchConfirmed: true,
    matches: '',
  },
  '-KyViTbBnDSNL-N4WTEq': {
    active: true,
    currentMatch: '-KgOvbJnHXFFk9IBqbSb',
    email: 'andrea.betancourt@yuxiglobal.com',
    firstName: 'Andrea',
    lastName: 'Betancourt',
    location: 1,
    matchConfirmed: true,
    matches: '',
  },
  '-KyViTbBnDSNL-N4WTEr': {
    active: true,
    currentMatch: '-KgOvebeq2vEcRECjba9',
    email: 'harvey.yepes@yuxiglobal.com',
    firstName: 'Harvey',
    lastName: 'Yepes',
    location: 1,
    matchConfirmed: true,
    matches: '',
  },
  '-KyViTbDcRpQEGj7hvjB': {
    active: true,
    currentMatch: '-KgOtNDgTpPsfQ6Ky2Sn',
    email: 'veronica.londono@yuxiglobal.com',
    firstName: 'Veronica',
    lastName: 'Londoño',
    location: 0,
    matchConfirmed: true,
    matches: '',
  },
  '-KyViTbDcRpQEGj7hvjC': {
    active: true,
    currentMatch: '-KgOwSDWw8_OxrNFbRlD',
    email: 'ronald.babilonia@yuxiglobal.com',
    firstName: 'Ronald',
    lastName: 'Babilonia',
    location: 0,
    matchConfirmed: true,
    matches: '',
  },
  '-KyW-ShEXpwL0A6viuiD': {
    active: true,
    currentMatch: '-KgOtgQXUHets4iMU4Sr',
    email: 'harvin.bejarano@yuxiglobal.com',
    firstName: 'Harvin',
    lastName: 'Bejarano',
    location: 1,
    matchConfirmed: true,
    matches: '',
  },
  '-KyW-ShIo7R-JN68ZUOU': {
    active: true,
    currentMatch: '-KgOvo9X5Ofa120BmH3y',
    email: 'laura.castro@yuxiglobal.com',
    firstName: 'Laura',
    lastName: 'Castro',
    location: 2,
    matchConfirmed: true,
    matches: '',
  },
  '-KyWpcaMh3GmeJYZ81jV': {
    active: true,
    currentMatch: '-KgOs4yXXBiQ62hBV67x',
    email: 'luis.palacios@yuxiglobal.com',
    firstName: 'Luis',
    lastName: 'Palacios',
    location: 1,
    matchConfirmed: true,
    matches: '',
  },
  '-KyWpcaQvrfDJHEQxltG': {
    active: true,
    currentMatch: '-KgOvrA9-7jV7c8i7Qwd',
    email: 'julian.rivas@yuxiglobal.com',
    firstName: 'Julian',
    lastName: 'Rivas',
    location: 1,
    matchConfirmed: true,
    matches: '',
  },
  '-KyWpcaROWIviAHeIRyx': {
    active: true,
    currentMatch: '-KnqjjFW6li72-Q_zLrS',
    email: 'jose.romero@yuxiglobal.com',
    firstName: 'Jose',
    lastName: 'Romero',
    location: 1,
    matchConfirmed: true,
    matches: '',
  },
  '-KyWpcaSt2iwMuN0EMAg': {
    active: true,
    currentMatch: '-KgOr6FlNMaAa-FUEbXG',
    email: 'samuel.mejia@yuxiglobal.com',
    firstName: 'Samuel',
    lastName: 'Mejia',
    location: 1,
    matchConfirmed: true,
    matches: '',
  },
  '-KyWpcaSt2iwMuN0EMAh': {
    active: true,
    currentMatch: '-KgOw9idQAbYbuT3k6gk',
    email: 'jose.rojas@yuxiglobal.com',
    firstName: 'Jose',
    lastName: 'Rojas',
    location: 0,
    matchConfirmed: true,
    matches: '',
  },
  '-KyWpcaTm0Pw2cJCAGre': {
    active: true,
    currentMatch: '-KgOqpjLOMXrEE1d1q3C',
    email: 'duverney.munoz@yuxiglobal.com',
    firstName: 'Duverney',
    lastName: 'Muñoz',
    location: 1,
    matchConfirmed: true,
    matches: '',
  },
  '-KyWpcaTm0Pw2cJCAGrf': {
    active: true,
    currentMatch: '-KkI0jYoXpkuX8fsLo7j',
    email: 'santiago.arango@yuxiglobal.com',
    firstName: 'Santiago',
    lastName: 'Arango',
    location: 2,
    matchConfirmed: true,
    matches: '',
  },
  '-KyWpcaU1xxfiWz8Ur8P': {
    active: true,
    currentMatch: '-KgOwPvl_TgHRx2Oyd_r',
    email: 'cristian.david@yuxiglobal.com',
    firstName: 'Cristian',
    lastName: 'Bedoya',
    location: 2,
    matchConfirmed: true,
    matches: '',
  },
  '-KyWpcaVCYoe33f9_M2H': {
    active: true,
    currentMatch: '-KgOrheOjx6lhIMZlgOk',
    email: 'deysi.sanchez@yuxiglobal.com',
    firstName: 'Deysi',
    lastName: 'Sanchez',
    location: 0,
    matchConfirmed: true,
    matches: '',
  },
  '-KyWpcaWs6CKLSM6PeDY': {
    active: true,
    currentMatch: '-KgoUYVSD1VZTTtvfHNp',
    email: 'juan.madrigal@yuxiglobal.com',
    firstName: 'Juan',
    lastName: 'Madrigal',
    location: 1,
    matchConfirmed: true,
    matches: '',
  },
};
